import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./components/QueryProvider";

export const metadata: Metadata = {
  title: "Briefly.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className="font-mulish antialiased bg-fixed bg-cover bg-center bg-[#0b0b0b] h-screen "
      // style={{ backgroundImage: "url('https://img.freepik.com/premium-photo/abstract-gradient-background-dark-gradient_1026065-86836.jpg')" }}
      >
        <QueryProvider>
          <div className="relative max-h-screen max-w-screen">
            <div className="relative z-10">{children}</div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}

