import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cover bg-center`}
        style={{
          backgroundImage: "url('/1092758.jpg')",  // Path to your background image
          backgroundSize: "cover",   // Ensures the image covers the entire page
          backgroundPosition: "center center",  // Centers the image both vertically and horizontally
          backgroundAttachment: "fixed", // Makes the background fixed during scrolling
          height: "100vh",  // Ensures the body covers the entire viewport height
        }}
      >
        <div className="relative max-h-[100vh] max-w-[100vw] overflow-hidden">
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}

